name: Retrieve AWS Secret

on:
  push:
    branches:
      - main

jobs:
  get-secret:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}  # Ensure this is added!

      - name: Retrieve AWS Secret
        run: |
          SECRET_VALUE=$(aws secretsmanager get-secret-value --secret-id mydemo01 --query SecretString --output text)
          echo "SECRET_VALUE=${SECRET_VALUE}" >> $GITHUB_ENV

      - name: Use the Secret
        run: echo "Secret Retrieved Successfully!"
